## L_03_1. Introduction to PyTorch Geometric

The aim of this notebook is to provide a very basic introduction to PyTorch geometric and to use the package for handling graphs. Have a look at https://pytorch-geometric.readthedocs.io/en/latest/get_started/introduction.html# 

### Modification for the assignment
This notebook now describes a different graph: a small campus map with 5 locations.
Nodes represent the dormitory, library, cafeteria, laboratory, and sports hall.
Edges model bidirectional walking paths, while each node feature stores two simple attributes: location importance and average daily traffic.

In [7]:
# Define a graph by indicating the edges and node features
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 0, 2, 1, 2, 1, 3, 2, 4, 3, 4],
                           [1, 0, 2, 0, 2, 1, 3, 1, 4, 2, 4, 3]], dtype=torch.long)
x = torch.tensor([[3.0, 120.0],
                  [4.0, 160.0],
                  [5.0, 210.0],
                  [2.0, 90.0],
                  [1.0, 70.0]], dtype=torch.float)

data1 = Data(x=x, edge_index=edge_index)

In [8]:
# Print / display data
print(data1)
print(data1.keys())
print(data1['x'])
print(f'Number of nodes: {data1.num_nodes}')
print(f'Number of edges: {data1.num_edges}')
for key, item in data1:
    print(f"{key} found in data1")
print(f'Has self loops: {data1.has_self_loops()}')
print(f'Has isolated nodes: {data1.has_isolated_nodes()}')

Data(x=[5, 2], edge_index=[2, 12])
['x', 'edge_index']
tensor([[  3., 120.],
        [  4., 160.],
        [  5., 210.],
        [  2.,  90.],
        [  1.,  70.]])
Number of nodes: 5
Number of edges: 12
x found in data1
edge_index found in data1
Has self loops: False
Has isolated nodes: False


In [9]:
torch.cuda.is_available()

False

In [10]:
# Transfer data object to GPU only when CUDA is available.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# data1 = data1.to(device)

In [11]:
# Define the same graph - alternative approach
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [0, 2],
                           [2, 0],
                           [1, 2],
                           [2, 1],
                           [1, 3],
                           [3, 1],
                           [2, 4],
                           [4, 2],
                           [3, 4],
                           [4, 3]], dtype=torch.long)
x = torch.tensor([[3.0, 120.0],
                  [4.0, 160.0],
                  [5.0, 210.0],
                  [2.0, 90.0],
                  [1.0, 70.0]], dtype=torch.float)

data2 = Data(x=x, edge_index=edge_index.t().contiguous())

In [12]:
# Print / display data
print(data2)
print(data2.keys())
print(data2['x'])
print(data2.edge_index.t())
for key, item in data2:
    print(f"{key} found in data2")
print(f'Has self loops: {data2.has_self_loops()}')
print(f'Has isolated nodes: {data2.has_isolated_nodes()}')

Data(x=[5, 2], edge_index=[2, 12])
['x', 'edge_index']
tensor([[  3., 120.],
        [  4., 160.],
        [  5., 210.],
        [  2.,  90.],
        [  1.,  70.]])
tensor([[0, 1],
        [1, 0],
        [0, 2],
        [2, 0],
        [1, 2],
        [2, 1],
        [1, 3],
        [3, 1],
        [2, 4],
        [4, 2],
        [3, 4],
        [4, 3]])
x found in data2
edge_index found in data2
Has self loops: False
Has isolated nodes: False
